SELECT 'PATIENTS' AS table_name, COUNT(*) AS row_count FROM patients
UNION ALL
SELECT 'DOCTORS', COUNT(*) FROM doctors
UNION ALL
SELECT 'SPECIALIZATIONS', COUNT(*) FROM specializations
UNION ALL
SELECT 'DOCTOR_SPECIALIZATIONS', COUNT(*) FROM doctor_specializations
UNION ALL
SELECT 'APPOINTMENTS', COUNT(*) FROM appointments
UNION ALL
SELECT 'CONSULTATIONS', COUNT(*) FROM consultations
UNION ALL
SELECT 'MEDICAL_RESULTS', COUNT(*) FROM medical_results
UNION ALL
SELECT 'ROLES', COUNT(*) FROM roles
UNION ALL
SELECT 'DB_USERS', COUNT(*) FROM db_users
UNION ALL
SELECT 'PRIVILEGES', COUNT(*) FROM privileges
UNION ALL
SELECT 'ROLE_PRIVILEGES', COUNT(*) FROM role_privileges;